### ISSUE TITLE
A typo in the installation step of README

### ISSUE THREAD

**Issue by yuifu** [yachielab/Interstellar#7]
Thank you for developing a very nice tool!

In the installation step of README(https://github.com/yachielab/Interstellar/blob/a1e6c59b75700199799d765d6d823780d1ff0bc2/README.md), I found a typo (See below). I think "Add the executable authority to Interstellar/py/*" should be outside of the code block.

```bash
git clone /URL/to/Interstellar.git Add the executable authority to Interstellar/py/*
```

**Comment by kijiy** [comment]
Hi, thank you so much for pointing it out!
